# Men's team unlikely to medal in floor

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('../../Combine_Data/men/fx_encoded.csv')
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_fx.csv')
fxnames = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_fxnames.csv')
fxolymp = pd.read_csv('../../Data/cleandata22-23/men22_23.csv')

In [3]:
df.head()

Rank    D      E   ND   Total  year  medal  Name  Nation  round_final  \
0     1  6.2  8.366  0.0  14.566  2019      0    71      56            1   
1     2  5.9  8.600  0.0  14.500  2019      0   119      40            1   
2     3  6.1  8.400  0.0  14.500  2019      1   245      25            1   
3     3  6.1  8.400  0.0  14.500  2019      0    94      81            1   
4     5  6.2  8.000  0.0  14.200  2019      0   166      64            1   

   round_qual  
0           0  
1           0  
2           0  
3           0  
4           0

In [4]:
import pandas as pd
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, fbeta_score, precision_recall_fscore_support


# Select features and target variable
X = df[['Rank', 'D', 'E', 'ND', 'Total', 'year', 'Name', 'Nation', 'round_final', 'round_qual']]
y = df['medal']

# Convert boolean values to 0 and 1
X['round_final'] = X['round_final'].astype(int)
X['round_qual'] = X['round_qual'].astype(int)

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Define the model
# (Same as the previous code)

# Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train_scaled, y_train, epochs=50, batch_size=2, verbose=1)

# Evaluate the model on the test set
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f'Test Loss: {loss:.4f}')
print(f'Test Accuracy: {accuracy:.4f}')

# Make predictions on the test set
y_pred = (model.predict(X_test_scaled) > 0.5).astype('int32')

# Calculate F2 score
f2 = fbeta_score(y_test, y_pred, beta=2)

# Display classification report and F2 score
print("Classification Report:\n", classification_report(y_test, y_pred))
print(f'F2 Score: {f2:.4f}')


2023-12-23 19:03:09.441377: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/var/folders/j_/555m2zps099832fjh_m8jjnc0000gn/T/ipykernel_49230/3180921025.py:15: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X['round_final'] = X['round_final'].astype(int)
/var/folders/j_/555m2zps099832fjh_m8jjnc0000gn/T/ipykernel_49230/3180921025.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentatio

NameError: name 'model' is not defined

In [5]:

y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(),
}

results = {}

# Iterate through each classifier
for name, clf in classifiers.items():
    # Create a pipeline with StandardScaler for classifiers that require it
    if name in ["SVM", "K-Nearest Neighbors", "Neural Network"]:
        clf = make_pipeline(StandardScaler(), clf)

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    results[name] = {
        "accuracy": accuracy,
        "classification_report": report,
        "confusion_matrix": conf_matrix,
    }

# Print the results
for name, result in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {result['accuracy']:.4f}")
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}\n")


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

Classifier: Random Forest
Accuracy: 0.9670
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.98        87
           1       1.00      0.25      0.40         4

    accuracy                           0.97        91
   macro avg       0.98      0.62      0.69        91
weighted avg       0.97      0.97      0.96        91

Confusion Matrix:
[[87  0]
 [ 3  1]]

Classifier: AdaBoost
Accuracy: 0.9780
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        87
           1       1.00      0.50      0.67         4

    accuracy                           0.98        91
   macro avg       0.99      0.75      0.83        91
weighted avg       0.98      0.98      0.97        91

Confusion Matrix:
[[87  0]
 [ 2  2]]

Classifier: SVM
Accuracy: 0.9560
Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.0

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.8/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Classifier: Decision Tree
Accuracy: 1.0000

Classifier: Random Forest
Accuracy: 1.0000

Classifier: AdaBoost
Accuracy: 1.0000


In [6]:
X_train.head()

Rank    D      E   ND   Total  year  Name  Nation  round_final  \
24     17  5.7  7.133  0.0  12.833  2019   255      65            0   
17     10  6.0  7.733  0.0  13.733  2019   210      41            0   
66     33  5.2  6.866 -0.1  11.966  2020    89      57            0   
302   165  5.3  7.566 -0.5  12.366  2019   128       8            0   
422     2  7.4  8.433  0.1  15.733  2014    12      40            1   

     round_qual  
24            1  
17            1  
66            1  
302           1  
422           0

In [7]:
olymp.head()


Rank  D Score  E Score  Pen.   Total  year  Name  nation  round_AAfinal  \
0  54.0      4.0    8.566   0.0  12.566  2023   154      59          False   
1  13.0      5.5    8.300   0.0  13.800  2022   354      27           True   
2  48.0      5.5    7.900   0.0  13.400  2022   354      27          False   
3  86.0      5.4    7.133   0.1  12.433  2022   354      27          False   
4  24.0      5.4    7.233   0.0  12.633  2023   354      27           True   

   round_TeamFinal  round_final  round_qual  
0            False        False        True  
1            False        False       False  
2            False        False        True  
3            False        False        True  
4            False        False       False

In [8]:
olymp.rename(columns={'D Score': 'D', 'E Score': 'E',
                     'Pen.': 'ND', 'nation': 'Nation'}, inplace=True)

In [9]:
olymp=olymp.drop(columns=['round_TeamFinal', 'round_AAfinal'])

In [10]:

y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.12, random_state=42)

# Initialize the AdaBoost classifier
clf = AdaBoostClassifier()

# Fit the model to the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print("AdaBoost Classifier")
print(f"Accuracy: {accuracy:.4f}")
print(f"Classification Report:\n{report}")
print(f"Confusion Matrix:\n{conf_matrix}")

AdaBoost Classifier
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        52
           1       1.00      1.00      1.00         3

    accuracy                           1.00        55
   macro avg       1.00      1.00      1.00        55
weighted avg       1.00      1.00      1.00        55

Confusion Matrix:
[[52  0]
 [ 0  3]]


In [11]:
y_pred = clf.predict(olymp)


In [12]:
ypreds  = pd.Series(y_pred)
olymp['ypred']=ypreds


In [13]:
olymp['ypred'].value_counts()

0    1362
1       3
Name: ypred, dtype: int64

In [14]:
filtered_df = olymp[olymp['ypred'] == 1]

In [15]:
filtered_df['Name'].unique()

array([363, 299, 301])

In [23]:
# fxnames[fxnames['Name_encoded']==432]

In [ ]:
fxnames

In [24]:
name_encoded_values = [363, 299, 301]

# Filter the DataFrame to get the corresponding "Name" values
result = fxnames.loc[fxnames['Name_encoded'].isin(name_encoded_values), 'Name']


In [25]:
result.unique()

array(['nicolau mir', 'luka van den keybus', 'luke whitehouse'],
      dtype=object)

In [21]:
fxolymp["Name"]=fxolymp["Name"].str.lower()

In [26]:
names_to_filter = ['nicolau mir', 'luka van den keybus', 'luke whitehouse']

# Filter the DataFrame to get rows with the specified "Name" values
result = fxolymp[fxolymp['Name'].isin(names_to_filter)]


In [27]:
result['Country'].value_counts()

GBR    39
ESP    28
BEL    24
Name: Country, dtype: int64