# USA unlikely to medal

In [1]:
import pandas as pd
import numpy as np
from scipy import stats
from mlxtend.preprocessing import minmax_scaling
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.datasets import make_circles, make_classification, make_moons
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.inspection import DecisionBoundaryDisplay
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [2]:
df = pd.read_csv('../../Combine_Data/men/hb_encoded.csv')
olymp = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_hb.csv')
hbnames = pd.read_csv('../../Data/cleandata22-23/encoded_m_olympics_hbnames.csv')
hbolymp = pd.read_csv('../../Data/cleandata22-23/men22_23.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 381 entries, 0 to 380
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Rank         381 non-null    int64  
 1   D            381 non-null    float64
 2   E            381 non-null    float64
 3   ND           381 non-null    float64
 4   Total        381 non-null    float64
 5   year         381 non-null    int64  
 6   medal        381 non-null    int64  
 7   Name         381 non-null    int64  
 8   Nation       381 non-null    int64  
 9   round_final  381 non-null    bool   
 10  round_qual   381 non-null    bool   
dtypes: bool(2), float64(4), int64(5)
memory usage: 27.7 KB


In [4]:

# Assuming you already have your DataFrame 'df' and the target variable is 'medal'
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize classifiers
classifiers = {
    "Random Forest": RandomForestClassifier(),
    "AdaBoost": AdaBoostClassifier(),
    "SVM": SVC(),
    "K-Nearest Neighbors": KNeighborsClassifier(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "Neural Network": MLPClassifier(),
}

results = {}

# Iterate through each classifier
for name, clf in classifiers.items():
    # Create a pipeline with StandardScaler for classifiers that require it
    if name in ["SVM", "K-Nearest Neighbors", "Neural Network"]:
        clf = make_pipeline(StandardScaler(), clf)

    # Fit the model to the training data
    clf.fit(X_train, y_train)

    # Make predictions on the test data
    y_pred = clf.predict(X_test)

    # Evaluate the model's performance
    accuracy = accuracy_score(y_test, y_pred)
    report = classification_report(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)

    results[name] = {
        "accuracy": accuracy,
        "classification_report": report,
        "confusion_matrix": conf_matrix,
    }

# Print the results
for name, result in results.items():
    print(f"Classifier: {name}")
    print(f"Accuracy: {result['accuracy']:.4f}")
    print(f"Classification Report:\n{result['classification_report']}")
    print(f"Confusion Matrix:\n{result['confusion_matrix']}\n")


/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, m

Classifier: Random Forest
Accuracy: 0.9740
Classification Report:
              precision    recall  f1-score   support

           0       0.97      1.00      0.99        73
           1       1.00      0.50      0.67         4

    accuracy                           0.97        77
   macro avg       0.99      0.75      0.83        77
weighted avg       0.97      0.97      0.97        77

Confusion Matrix:
[[73  0]
 [ 2  2]]

Classifier: AdaBoost
Accuracy: 0.9870
Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        73
           1       1.00      0.75      0.86         4

    accuracy                           0.99        77
   macro avg       0.99      0.88      0.93        77
weighted avg       0.99      0.99      0.99        77

Confusion Matrix:
[[73  0]
 [ 1  3]]

Classifier: SVM
Accuracy: 0.9610
Classification Report:
              precision    recall  f1-score   support

           0       0.96      1.0

/Users/ryantalbot/opt/anaconda3/envs/tf2/lib/python3.9/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Classifier: Decision Tree
Accuracy: 0.9870

Classifier: AdaBoost
Accuracy: 0.9870

In [5]:
X_train.head()

Rank    D      E   ND   Total  year  Name  Nation  round_final  \
78     20  4.5  8.700  0.0  13.200  2019    84      26        False   
265   149  4.9  7.233  0.0  12.133  2019   154       9        False   
93     35  4.4  8.100  0.0  12.500  2019    98       4        False   
377    19  5.1  7.400  0.0  24.600  2020    12      74         True   
272   156  4.4  7.600  0.0  12.000  2019   239      68        False   

     round_qual  
78         True  
265        True  
93         True  
377       False  
272        True

In [6]:
olymp.head()


Rank  D Score  E Score  Pen.   Total  year  Name  nation  round_AAfinal  \
0  39.0      4.6    6.700   0.0  11.300  2023   150      57          False   
1  44.0      4.6    8.166   0.0  12.766  2023   151      57          False   
2  10.0      5.3    8.133   0.0  13.433  2022   353      26           True   
3  48.0      5.0    8.166   0.0  13.166  2022   353      26          False   
4  10.0      5.3    8.500   0.0  13.800  2022   353      26          False   

   round_TeamFinal  round_final  round_qual  
0            False        False        True  
1            False        False        True  
2            False        False       False  
3            False        False        True  
4            False        False        True

In [7]:
olymp.rename(columns={'D Score': 'D', 'E Score': 'E',
                     'Pen.': 'ND', 'nation': 'Nation'}, inplace=True)

In [8]:
olymp=olymp.drop(columns=['round_TeamFinal', 'round_AAfinal'])

In [9]:

# Assuming you already have your DataFrame 'df' and the target variable is 'medal'
y = df['medal']
X = df.drop(columns=['medal'])

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.12, random_state=42)

# Initialize the AdaBoost classifier
# CHANGING LEARNIN RATE TO 0.31 RESULTS IN 1.000 
clf = AdaBoostClassifier(n_estimators=100, learning_rate=0.41)

# Fit the model to the training data
clf.fit(X_train, y_train)

# Make predictions on the test data
y_pred = clf.predict(X_test)

# Evaluate the model's performance
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)

# Print the results
print("AdaBoost Classifier")
print(f"Accuracy: {accuracy:.4f}")
print(f"Classification Report:\n{report}")
print(f"Confusion Matrix:\n{conf_matrix}")

AdaBoost Classifier
Accuracy: 1.0000
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        42
           1       1.00      1.00      1.00         4

    accuracy                           1.00        46
   macro avg       1.00      1.00      1.00        46
weighted avg       1.00      1.00      1.00        46

Confusion Matrix:
[[42  0]
 [ 0  4]]


In [10]:
y_pred = clf.predict(olymp)


In [11]:
ypreds  = pd.Series(y_pred)
olymp['ypred']=ypreds


In [12]:
olymp['ypred'].value_counts()

ypred
0    1342
1       5
Name: count, dtype: int64

In [13]:
filtered_df = olymp[olymp['ypred'] == 1]

In [14]:
filtered_df['Name'].unique()

array([448, 469,  55])

In [20]:
name_encoded_values = [448, 469,  55]

# Filter the DataFrame to get the corresponding "Name" values
result = hbnames.loc[hbnames['Name_encoded'].isin(name_encoded_values), 'Name']


In [21]:
result.unique()

array(['shohei kawakami', 'tin srbic', 'boheng zhang'], dtype=object)

In [22]:
hbolymp["Name"]=hbolymp["Name"].str.lower()

In [23]:
names_to_filter = ['shohei kawakami', 'tin srbic', 'boheng zhang']

# Filter the DataFrame to get rows with the specified "Name" values
result = hbolymp[hbolymp['Name'].isin(names_to_filter)]

In [24]:
result['Country'].value_counts()

Country
CHN    25
JPN    13
CRO    12
Name: count, dtype: int64