In [2]:
import pandas as pd
import numpy as np

In [3]:
mfx = pd.read_csv('../Combine_Data/men/fx_encoded.csv')
mvt = pd.read_csv('../Combine_Data/men/vt_encoded.csv')
mhb = pd.read_csv('../Combine_Data/men/hb_encoded.csv')
mpb = pd.read_csv('../Combine_Data/men/pb_encoded.csv')
mph = pd.read_csv('../Combine_Data/men/ph_encoded.csv')
msr = pd.read_csv('../Combine_Data/men/sr_encoded.csv')
miaa = pd.read_csv('../Combine_Data/men/iaa_encoded.csv')


In [4]:
miaa['year'].unique()

array([2018., 2019.,   nan])

In [5]:
mfx['year'].unique()

array([2019, 2020, 2018])

In [6]:
mvt['year'].unique()

array([2019, 2018, 2020])

In [7]:
mhb['year'].unique()

array([2019, 2020, 2018])

In [8]:
mpb['year'].unique()

array([2019, 2020, 2018])

In [9]:
msr['year'].unique()

array([2019.,   nan, 2018., 2020.])

In [10]:
mph['year'].unique()

array([2019, 2020, 2018])

In [11]:
len(mvt)

126

In [12]:
len(mfx)

538

In [13]:
len(mhb)

502

In [14]:
len(mpb)

485

In [15]:
len(mph)

535

In [16]:
len(msr)

495

In [17]:
len(miaa)

512

vault 126
floor 538
high bar 502
parallel bar 485
pommel horse 535
rings 495


In [18]:
data = {'Apparatus': ['Vault', 'Floor', 'High Bar', 'Parallel Bar', 'Pommel Horse', 
                      'Rings', 'IAA'],
        'Scores': [126, 538, 502, 485, 535, 495, 512],
        'years': ['2018-2020','2018-2020','2018-2020','2018-2020','2018-2020',
                  '2018-2020', '2018-2019']
}

# Creating DataFrame
df = pd.DataFrame(data)
df

Apparatus  Scores      years
0         Vault     126  2018-2020
1         Floor     538  2018-2020
2      High Bar     502  2018-2020
3  Parallel Bar     485  2018-2020
4  Pommel Horse     535  2018-2020
5         Rings     495  2018-2020
6           IAA     512  2018-2019

In [19]:
df= df.drop(columns=['years'])

In [20]:
df.loc['Sum'] = ['Total', df['Scores'].sum()]

In [21]:
df

Apparatus  Scores
0           Vault     126
1           Floor     538
2        High Bar     502
3    Parallel Bar     485
4    Pommel Horse     535
5           Rings     495
6             IAA     512
Sum         Total    3193

In [22]:
df.rename(columns={'Event': 'Events', 'Data Size': 'Individual Entries'}, inplace=True)

In [23]:
df

Apparatus  Scores
0           Vault     126
1           Floor     538
2        High Bar     502
3    Parallel Bar     485
4    Pommel Horse     535
5           Rings     495
6             IAA     512
Sum         Total    3193

In [24]:
ffx = pd.read_csv('../Combine_Data/women/fx_encoded.csv')
fvt = pd.read_csv('../Combine_Data/women/vt_encoded.csv')
fbb = pd.read_csv('../Combine_Data/women/bb_encoded.csv')
fub = pd.read_csv('../Combine_Data/women/ub_encoded.csv')
wiaa = pd.read_csv('../Combine_Data/women/iaa_encoded.csv')


In [25]:
ffx['year'].unique()

array([2019, 2020, 2018, 2017, 2015, 2014, 2013, 2016])

In [26]:
wiaa['year'].unique()

array([2018, 2019])

In [27]:
fbb['year'].unique()

array([2019, 2020, 2018, 2017, 2021, 2016, 2015, 2013, 2014])

In [28]:
fvt['year'].unique()

array([2018., 2019., 2020., 2017., 2013., 2014., 2016., 2015.])

In [29]:
fub['year'].unique()

array([2019, 2020, 2018, 2017, 2015, 2014, 2013, 2016])

In [30]:
len(ffx)

438

In [31]:
len(fvt)

145

In [32]:
len(fbb)

587

In [33]:
len(fub)

446

In [34]:
len(wiaa)

537

In [35]:
data = {'Event': ['Floor', 'Vault', 'Balance Beam', 'Uneven Bars', 'IAA'],
        'Data Size': [438, 145, 587, 446, 537],
       'years': ['2013-2020','2013-2020', '2013-2021', '2013-2020', '2018-2019'] }

# Creating DataFrame
df = pd.DataFrame(data)
df

Event  Data Size      years
0         Floor        438  2013-2020
1         Vault        145  2013-2020
2  Balance Beam        587  2013-2021
3   Uneven Bars        446  2013-2020
4           IAA        537  2018-2019

In [36]:
df= df.drop(columns=['years'])

In [37]:
df.loc['Sum'] = ['Total', df['Data Size'].sum()]

In [38]:
df

Event  Data Size
0           Floor        438
1           Vault        145
2    Balance Beam        587
3     Uneven Bars        446
4             IAA        537
Sum         Total       2153

In [104]:
df.rename(columns={'Event': 'Events', 'Data Size': 'Individual Entries'}, inplace=True)

In [105]:
df

Events  Individual Entries
0           Floor                 438
1           Vault                 145
2    Balance Beam                 587
3     Uneven Bars                 446
4            wiaa                 537
Sum         Total                2153