# Introduction to Numpy and Pandas
***

**NumPy** is an open source Python package for scientific computing. NumPy supports large, multidimensional arrays and matrices. It also supports a large collection of mathematical functions not found in Python's standard math library.

**Pandas** is an open source data analysis library in Python used for storing, cleaning, wrangling, and analyzing data.  

First, let's import the Numpy and Pandas libraries.  It's custom in data science to import Pandas and Numpy  with the aliases $\texttt{pd}$, and $\texttt{np}$, respectively.  We can then access any function in the Numpy or Pandas libraries by prepending function names by $\texttt{np.}$ or $\texttt{pd.}$.  

In [1]:
import pandas as pd
import numpy as np 

### The Numpy ndarray

The main workhorse of Numpy is it's multidimensional array class called the $\texttt{ndarray}$.  This allows us to build and work with one dimensional, two dimensional, or even $N$-dimensional arrays of numbers. 

We can build a one dimensional ndarray by passing a Python list to the $\texttt{np.array()}$ function. 

In [4]:
x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


We can check the type of the array that we've just created with Python's type command.

In [5]:
type(x)

numpy.ndarray

The nice thing about using Numpy arrays to store numerical values is that we can perform mathematical operations on them.  For instance, if we want to multiply every value in $\texttt{x}$ by $5$ and store the result in a new array $\texttt{y}$ we can do so as follows: 

In [6]:
y = 5*x
print(y)

[ 5 10 15 20 25]


If we want to add two ndarray's of equal length together we can do that too: 

In [7]:
z = x + y 
print(z)

[ 6 12 18 24 30]


If we want to create a two dimensional array we simply pass a list of lists to the $\texttt{np.array()}$ function.  The lists in the list of lists then become the rows of the two dimensional array. 

In [8]:
A = np.array([[1,2,3,4,5], [6,7,8,9,10]], dtype=float)
print(A)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


We can access elements of Numpy arrays in a ways similar to the way we access elements in Python lists. For instance, if we want to get the first $3$ elements of the array $\texttt{y}$, we can do so as follows: 

In [9]:
print(y)

[ 5 10 15 20 25]


In [11]:
y[0:4]

array([ 5, 10, 15, 20])

Just like with Python lists, if we're indexing from the start of the array there is no need to include the $0$ in the index range.  We can simply do 

In [ ]:
y[:3]

Similarly, if we want to access everything from the third entry to the end of the array, we can do 

In [ ]:
y[2:]

Indexing in multidimensional arrays is similar.  First, let's build a two dimensional array with our arrays $\texttt{x}, \texttt{y},$ and $\texttt{z}$ as the rows. 

In [ ]:
B = np.array([x,y,z])
print(B)

We can slice up the two dimensional array by doing slices along rows and columns.  Let's suppose we wanted to carve out the second row of $\texttt{B}$. 

In [ ]:
B[1,:]


Here, the stuff before the comma refers to rows of the array, and the stuff after the comma refers to columns of the array.  In the previous command we've indicated that we want the row with index $1$, and the colon indicated that we want _all_ of the columns. Similarly, if we want all of the fourth column, we could do 

In [ ]:
B[:,3]

If you've played with slicing lists of Python lists then you'll note that the main difference between slicing two dimensional Numpy arrays is that we only need one set of brackets, instead of two. Otherwise it's pretty similar.   

If we want to carve out certain rows and certain columns, we can do that by grabbing ranges of indices for both the rows and the columns.  For instance, if we want the part of $\texttt{B}$ in the second and third rows and the second through the fourth columns we can do 

In [ ]:
B[1:3, 1:4]

We can also apply mathematical functions to the two dimensional array.  For instance, if we want to sum all of the entries in $\texttt{B}$ we can do 

In [ ]:
np.sum(B)

If instead we just want to sum along the rows or columns of the array we can add the $\texttt{axis}$ parameter.  

In [ ]:
np.sum(B, axis=0)

Notice that choosing $\texttt{axis=0}$ caused us to sum along the columns of $\texttt{B}$.  If instead we used $\texttt{axis=1}$ we would sum along the rows 

In [ ]:
np.sum(B, axis=1)

We can also index into an array by conditions.  For instance, remember the vector $\texttt{z}$

In [ ]:
print(z)

Let's suppose I want to grab all of the entries in $\texttt{z}$ that are bigger than $15$.  The condition $\texttt{z > 15}$ returns a boolean array indicating whether each entry in $\texttt{z}$ satisfies the given condition 

In [ ]:
z > 15

Now, if I want to actually extract those entries of $\texttt{z}$ that satisfy the condition we can index $\texttt{z}$ using this boolean array 

In [ ]:
z[z>15]


### Numpy Mathematical Functions

Numpy includes all of the functions and mathematical constants in Python's standard math library, like logarithms, exponentiation, and even $\pi$.  

In [ ]:
print(np.log(np.exp(1)))
print(np.log2(16))
print(np.log10(1000))
print(np.pi)

The nice thing about Numpy's mathematical functions is that they can be applied to arrays as well as scalars.  For instance

In [ ]:
u = [10, 100, 1000, 10000]
np.log10(u)

### Pandas Data Structures

Pandas has two types of data structures: 
- The **Series**: A one dimensional array with labeled indices. 
- The **Dataframe**: A tabular spreadsheet-like structure with rows and columns. 


### The Pandas Series

First we'll create a Series with a list of integer values

In [12]:
my_series = pd.Series([17,3,7,9,8,10])

We can print the Series object by executing the series name in a Python cell 

In [13]:
my_series

0    17
1     3
2     7
3     9
4     8
5    10
dtype: int64

Note that this displayed multiple outputs.  The first column lists the default indices of the entries in the Series.  The second column lists the actual values of the Series.  Finally, the last line of output tells us the type of the values of the Series. 

If we want a simple array containing the value of the Series we can access this with the $\texttt{.values}$ attribute. 

In [14]:
my_series.values

array([17,  3,  7,  9,  8, 10])

Note that this returns a simple array type containing the values of the Series.  In fact, this is actually a Numpy ndarray, which we can verify by asking Python for the type of $\texttt{my_series.values}$. 

In [ ]:
type(my_series.values)

We can also obtain an array of the indices associated with the Series using the $\texttt{.index}$ attribute.  

In [ ]:
my_series.index

In this case the data type of $\texttt{my_series.index}$ is a Pandas RangeIndex, which is sort of like an ordered integer array.  

OK, so far we've defined a basic Pandas Series that uses the default indices.  Typically, if we think of the index as a label describing where the piece of data in the series came from, it's useful to define our own custom indices.  For example, we could create a series listing the FY 2016 revenue (in billions of \$) of the 5 largest information technology companies ([source](https://en.wikipedia.org/wiki/List_of_the_largest_information_technology_companies))

In [15]:
top_tech2016 = pd.Series([215.6, 173.9, 135.9, 135.1, 90.2], 
                         index=["Apple", "Samsung", "Amazon", "Foxconn", "Alphabet"])

In [16]:
top_tech2016

Apple       215.6
Samsung     173.9
Amazon      135.9
Foxconn     135.1
Alphabet     90.2
dtype: float64

Notice that the indices of the Series are now strings corresponding to the names of the companies, while the values are floats representing each company's revenue.  

Now suppose that we only care about the _really_ high performers, and want the subset of the Series corresponding to companies that had revenue in excess of \$100B.  We can index into the Series using a boolean condition, much like we did with Numpy arrays: 

In [18]:
top_tech2016[top_tech2016 > 100]
top_tech2016>100

Apple        True
Samsung      True
Amazon       True
Foxconn      True
Alphabet    False
dtype: bool

When Series are very large it's important to be able to check if particular elements are in the Series without having to scan through with our eyeballs.  Here we can check if companies Amazon and AT&T are part of the Series. 

In [19]:
"Amazon" in top_tech2016

True

In [20]:
"AT&T" in top_tech2016

False

### The Pandas DataFrame

The key data structure in Pandas is the **DataFrame** object. A DataFrame is basically a tabular data structure, with rows and columns. Rows have a specific index to access them, which can be any name or value. The columns are just Pandas Series. The Pandas DataFrame data structure can be seen as a spreadsheet, but it is much more flexible. 

First, let's create a DataFrame from scratch by passing in a Python dictionary. The following data records the records of three Spanish soccer teams during the years 2010-2013. 

In [21]:
data = {'year': [2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012],
        'team': ['FCBarcelona', 'FCBarcelona', 'FCBarcelona', 'RMadrid', 'RMadrid', 'RMadrid', 'ValenciaCF',
                 'ValenciaCF', 'ValenciaCF'],
        'wins':   [30, 28, 32, 29, 32, 26, 21, 17, 19],
        'draws':  [6, 7, 4, 5, 4, 7, 8, 10, 8],
        'losses': [2, 3, 2, 4, 2, 5, 9, 11, 11]
        }

We'll convert this data to a Pandas DataFrame as follows: 

In [22]:
football = pd.DataFrame(data)
print(football)

   year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11


Note that each list in the dictionary has become a column in our DataFrame with the associated dictionary key as the column name.  

Now, the order that the columns are situated is a little weird (note that by default it did it alphabetically).  If instead we want the columns in the order _year_, _team_, _wins_, _draws_, _losses_ we can pass this ordering of the columns in when we create the DataFrame. 

In [ ]:
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'draws', 'losses'])
print(football)

Much better. 

Here we've displayed the DataFrame using the standard Python $\texttt{print()}$ function, but Pandas has it's own spread-sheet-like way of displaying data.  If we want to see the first 5 rows of the DataFrame we can use the $\texttt{.head()}$ method. 

In [23]:
football.head()

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2

If we want to see more rows we can pass in an optional argument into $\texttt{.head()}$. 

In [24]:
football.head(8)

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11

If we want to see the last $5$ rows of the DataFrame we can use the $\texttt{.tail()}$ method. 

In [28]:
football

year         team  wins  draws  losses
0  2010  FCBarcelona    30      6       2
1  2011  FCBarcelona    28      7       3
2  2012  FCBarcelona    32      4       2
3  2010      RMadrid    29      5       4
4  2011      RMadrid    32      4       2
5  2012      RMadrid    26      7       5
6  2010   ValenciaCF    21      8       9
7  2011   ValenciaCF    17     10      11
8  2012   ValenciaCF    19      8      11

### Adding Columns to Pandas DataFrames

In many sporting events it is customary to rank the performances of different teams by taking a weighted sum of the win, loss, and draws in a season.  In particular, it is customary to award 3 points for each win, 1 point for each draw, and 0 points for each loss.  Let's compute this point total for each team-season combination stored in the data frame, and store it in a new column called **points**. We can do this as follows

In [ ]:
football["points"] = 3*football["wins"] + 1*football["draws"] + 0*football["losses"]
football

There are several takeaways from this exercise.  First, if we want to create a new column in our DataFrame, we simply have to assign the DataFrame indexed by the new column name to some valid Panda Series.  The second takeaway is that we can scale and add Pandas Series in the same way we can with Numpy arrays. 

### Sorting in Pandas

Now suppose we want to rank the team-season combinations from greatest to least number of points.  One way we could do this would be to sort the DataFrame by the **points** column.  We can do this as follows:

In [ ]:
football_sorted = football.sort_values(by="points", ascending=False)
football_sorted

It looks like it's a tie between 2012 FC Barcelona and 2011 Real Madrid.  

There are a couple of things to notice here.  First, the sort_values method actually returns a new DataFrame, with the data sorted as requested.  If instead we wanted to modify the existing DataFrame so that it's values are sorted we could have added the "inplace=True" parameter to the sort_values method.  For now though we'll leave the original football DataFrame as it is. 

The second interesting thing to notice is that the DataFrame indices (the first column) have been rearranged as well.  In truth, the indices of a DataFrame are only numbers by default.  We could also set them to be other unique identifiers like strings.  In that setting, in makes perfect sense that they should tag along with their original data. 

### Slicing and Dicing Pandas DataFrames

The sorted football DataFrame gives us an opportunity to talk about the intricacies of selecting data from Pandas DataFrames.  There are two main methods that we will use to slice and dice data from DataFrames: $\texttt{loc}$ and $\texttt{iloc}$. Note that if you've used Pandas in the past, you might have seen the method $\texttt{ix}$ which is deprecated in the current version of Pandas, so we shall avoid it. 

We'll explicitly write down the differences between $\texttt{loc}$ and $\texttt{iloc}$ here, because it's a bit hard to remember

- $\texttt{loc}$ slices rows and columns by their **names** 
- $\texttt{iloc}$ slices rows and columns by their **integer index order**, much like slicing in Numpy 

At first, we'll just worry about selecting certain rows.  Shift-enter these two cells and see if you can pick up on the different behaviors

In [ ]:
football_sorted.iloc[:4]

In [ ]:
football_sorted.loc[:4]

Do you see the difference?  $\texttt{iloc[:4]}$ sliced out the first 4 rows of the DataFrame, ignoring what the rows happened to be named. 

On the other hand,  $\texttt{loc[:4]}$ sliced out the rows in the sorted DataFrame from the beginning until we found the row **named** 4 by it's index. 


Now suppose we want the first four rows of the DataFrame, but only the first three colums.  Since we're slicing by integer order, we'll use $\texttt{iloc}$.  We have

In [ ]:
football_sorted.iloc[:4,:3]

Now, suppose that we want to mix slicing by numerical order and slicing by name.  This can get kinda tricky. For instance, suppose we wanted the first four rows of the DataFrame, and just the columns corresponding to **team** and **points**.  So we're really doing two slices: one by integer index order, and one by name.  One **INADVISABLE** way to do this is to chain multiple calls to $\texttt{iloc}$ and $\texttt{loc}$ together. 

In [ ]:
football_sorted.iloc[:4].loc[:,["team", "points"]]

This works because $\texttt{football_sorted.iloc[:4]}$ returns a DataFrame which we then apply $\texttt{loc[:,["team", "points"]]}$ to.  The problem with this is that the actual object that is returned by this can be unpredictable.  We won't go into too much detail about this, but if you're interested in reading more, you can do so in the Pandas documentation [here](https://pandas.pydata.org/pandas-docs/stable/indexing.html#returning-a-view-versus-a-copy). Rest assured, if you ever go this route, Pandas will scream a lot of fun warnings at you. 

A better thing to do is use $\texttt{loc}$ and then use a trick to get the named indices of the first four rows.  We can do this as follows: 

In [ ]:
football_sorted.loc[football_sorted.index[:4], ["team", "points"]]

This worked because $\texttt{football_sorted.index[:4]}$ returns the names of the first four rows, which you can check here

In [ ]:
football_sorted.index[:4]

We can also select rows of a DataFrame using conditions, much like you can do with Numpy arrays.  For this, let's go back to the original $\texttt{football}$ DataFrame, which we reprint here for your recollection. 

In [ ]:
football

Suppose we want to select all of the team-season combinations where the total number of points was greater than 95.  Much like in Numpy, we can simply write down a logical comparison of the **points** column with the desired value. 

In [ ]:
football["points"] > 95

In this case, what we get out is a Pandas Series with boolean values, indicating whether each row of the DataFrame passes the condition. We can then pass this into the $\texttt{loc}$ method to get all of the rows of the DataFrame that satisfy the condition. 

In [ ]:
football.loc[football["points"] > 95]

Note that we could have just passed the conditioned into the DataFrame itself, as 

In [ ]:
football[football["points"] > 95]

The problem with this, is that if we decide we only want to see the _year_ and _team_ columns associated with this condition, we're now motivated to create a dastardly selection chain, which we just decided we shouldn't do.  Instead we'll use the safe $\texttt{loc}$ method. 

In [ ]:
football.loc[football["points"] > 95, ["year", "team"]]

We can also combine logical conditions together.  Suppose we want to know if any teams scored more than $95$ points in the years 2011 or 2012.  For this, we can do 

In [ ]:
football.loc[(football["points"] > 95) & (football["year"] >= 2011), ["year", "team"]]

**IMPORTANT NOTE**: When doing logical operations in Pandas, we use $\texttt{&}$ and $\texttt{|}$ for _and_ and _or_, respectively.  This differs from the traditional $\texttt{and}$ and $\texttt{or}$ connectives used in Python. 

In [ ]:
football

### Manipulating Data 

Often times we want to apply mathematical functions element-wise to columns or entire chunks of a DataFrame. We can do this with the $\texttt{apply()}$ function. If you're familiar with Python's $\texttt{map()}$ function, it's very similar. 

Let's suppose, for whatever reason, you want to know the square root of the number of points for each team-season combination.  We can do this by using the $\texttt{apply()}$ function on the **points** column with Numpy's square root function as the argument. 

In [ ]:
football["points"].apply(np.sqrt)

Note that this applies the function $\texttt{np.sqrt()}$ to each entry in the **points** Series, and returns a Pandas series as a result. 

Often times we want to apply our own cooked up functions to elements of a Series.  We can do this using Python $\texttt{lambda}$ functions.  As a simple example, let's suppose we want to square every element in the **points** column.  We do this like so 

In [ ]:
football["points"].apply(lambda x: x**2)

A $\texttt{lambda}$ function is a function without a name. The variable after the **lambda** is simply a dummy variable representing the element of the series being passed to the function.  The part after the **:** specifies what the function should do to the input variable.  

$\texttt{lambda}$ functions are particularly useful for doing string manipulation.  Suppose for instance we wanted to convert all of the team names from the **team** column to lowercase.  For this we'll use a $\texttt{lambda}$ function and $\texttt{apply}$ to apply the $\texttt{lower()}$ method to each team name.  

In [ ]:
football["team"].apply(lambda s: s.lower())

### Grouping Data

Another very useful way to inspect data is to group it according to some criteria. For instance, in our example it would be nice to group all the data by the particular soccer team, regardless of the year. Pandas has the **groupby** function that allows us to do just that. The value returned by this function is a special grouped DataFrame. To have a proper DataFrame as a result, it is necessary to apply an aggregation function. Thus, this function will be applied to all the values in the same group.

For example, in our case, if we want a DataFrame showing the mean of the total **points** earned by each team over all the years, we can obtain it by grouping according to **team** and using the mean function as the aggregation method for each group. The result would be  a DataFrame with teams as indexes and the mean values as the column:

In [ ]:
football[["team", "points"]].groupby("team").mean()

Sometimes you want to perform groupby operations on multiple columns simultaneously.  Consider the following DataFrame containing **Class**, **Sex**, and **Age** characteristics for passengers on the Titanic. 

In [ ]:
dfPassengers = pd.DataFrame({"Class": [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2], 
                   "Sex": ["male", "female", "male", "female", "male", "female", "male", "male", "male", "female", "female", "female"],
                   "Name": ["Dave", "Rhonda", "Frank", "Rachel", "Tony", "Elle", "Chris", "Maciej", "Brian", "Ioana", "Danielle", "Maribeth"],
                   "Age": [32, 45, 47, 12, 17, 13, 75, 85, 12, 37, 38, 40]}, columns=["Class", "Sex", "Name", "Age"])
dfPassengers

Suppose we want to determine the average age of men in 1st class, women in 1st class, men in 2nd class, and women in 2nd class.  We can do a groupby on both **Class** and **Sex**, and then call Numpy's mean function as the aggregation function on the **Age** column. We'll store the result in the DataFrame dfMeanAge. Note that we want to store the result in a column called **Mean Age** so we pass to the agg function a dictionary where the key is the new column name, and the value is the function we want to apply. 

In [ ]:
dfMeanAge = dfPassengers.groupby(["Class", "Sex"], as_index=False)["Age"].agg({"Mean Age" : np.mean})
dfMeanAge

The **as_index=False** parameter ensures that the groupby operation returns a DataFrame. 

We can also perform groupby aggregation operations with custom functions. Suppose, for example, we want to know the number of passengers aged 18 years or younger in each class-sex combination.  We can do this by passing a custom function into the .agg( ) method. We'll show the example here and then explain how it works.  

In [ ]:
def num_children(vec):
    
    # Get a boolean array indicating whether 
    # the passenger is 18 or younger 
    is_child = vec <= 18
    
    # Count the number of Trues in the array 
    num_child = np.sum(is_child)
    
    # Return the value 
    return num_child

dfNumChildren = dfPassengers.groupby(["Class", "Sex"], as_index=False)["Age"].agg({"Num Children" : num_children})
dfNumChildren

When we pass the result of the groupby operation into the agg function, it extracts the entries of **Age** corresponding to each group and passes them into your custom function as a Numpy array.  Hence, the vec variable in the num_children function is actually an array which we can then do array-like operations on.  Because we're _aggregating_ the results from a vector, the return value for your custom aggregation function should almost always be a single value (int, float, or string).   

OK, so now we have the two DataFrames dfMeanAge and dfNumChildren which are remarkably similar in the sense that they both have corresponding **Class** and **Sex** columns, and they share common indices.  They only differ in the extra **Mean Age** and **Num Children** columns that we have created.  It would be nice if we could get all of these things into one DataFrame.  Luckily, Pandas gives us the merge function, which we use as follows.  

In [ ]:
dfMerged = pd.merge(dfMeanAge, dfNumChildren)
dfMerged

Note that we now have all of our aggregation results int he same DataFrame. 

OK, let's do one more important groupby example.  Suppose we want to know the **Name** of the oldest person in each Class-Sex combination.  There are several ways to do this, but the most straightforward is to use a groupby operation to find the _indices_ of the rows corresponding to the max age in each group.  We can then slice the appropriate names out of the original DataFrame. 

In [ ]:
dfPassengers

In [ ]:
oldest_indices = dfPassengers.groupby(["Class", "Sex"])["Age"].agg('idxmax')
print(oldest_indices)

We can check in the original DataFrame that Maceij, the person in row 7, is in fact the oldest passenger in the Class=2, Sex=male category.  

Now we can use the oldest_indices series to extract the **Name** of the oldest people from the original DataFrame. 

In [ ]:
dfOldest = dfPassengers.loc[oldest_indices, ["Class", "Sex", "Name"]]
dfOldest

We'd can now merge this DataFrame in with our combined DataFrame showing **Mean Age** and **Num Children**.  

In [ ]:
dfClassSex = pd.merge(dfMerged, dfOldest)
dfClassSex

The last nagging thing we want to fix is that the original **Name** is not very descriptive.  We'd like to rename that column to something like **Oldest Passenger**.  We can do that with the rename function. 

In [ ]:
dfClassSex.rename(columns={"Name" : "Oldest Passenger"}, inplace=True)
dfClassSex

# Further Reading

We've just barely scratched the surface of what Pandas and Numpy can do.  As we move forward in the course we'll learn how to apply various statistical functions to data, how to make plots and charts based on data, and how to clean and wrangle messy data.  

If you want to explore more of what Pandas can do, check out the (very readable) pandas docs for more information

http://pandas.pydata.org/pandas-docs/stable/